import { Booking, insertBooking, findBookingByCustomerId, removeBooking } from "../models/booking.js";

async function bookHotel(req, res, next) {
    const {
        status,
        destinationId,
        hotelId,
        roomKey,
        customerId,
        numberOfNights,
        startDate,
        endDate,
        numAdults,
        numChildren,
        msgToHotel,
        roomTypes,
        price,
        guestSalutation,
        guestFirstName,
        guestLastName,
        paymentId,
        payeeId} = req.body;

    // Step 1: Process payment

    // Step 2: If payment successful, create booking
    // pass in dummy value for bookingId: this will be auto-generated by SQL database as primary key and returned to us once the booking is inserted
    const booking = Booking(null,
        status,
        destinationId,
        hotelId,
        roomKey,
        customerId,
        numberOfNights,
        startDate,
        endDate,
        numAdults,
        numChildren,
        msgToHotel,
        roomTypes,
        price,
        guestSalutation,
        guestFirstName,
        guestLastName,
        paymentId,
        payeeId);

    const bookingId = await insertBooking(booking); // Booking ID generated by database upon insertion (auto-increment primary key)

    // (Extension) Step 2.5: If user logged in, associate booking with their account (need to consider security)

    // Step 3: Send booking confirmation email

    // Step 4: respond back with success message
}