name: Run tests

on: [ push ]

jobs:
  test-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        working-directory: ./server
        run: npm install
      - name: Run tests
        working-directory: ./server
        run: npm test
      - name: Upload JUnit Test Report
        uses: actions/upload-artifact@v3
        with:
          name: jest-junit-server-report
          path: ./server/reports/jest-junit.xml
  # test-client:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Use Node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: '20.x'
  #     - name: Install dependencies
  #       working-directory: ./client
  #       run: npm install
  #     - name: Run tests
  #       working-directory: ./client
  #       run: npm test
